<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: alice
 * Date: Fri, 05 Dec 2008 14:01:01 +0000
 */

$conf['title'] = '';
$conf['lang'] = 'de';
$conf['template'] = 'std';
$conf['license'] = '';
$conf['maxtoclevel'] = '0';
$conf['maxseclevel'] = '2';
$conf['deaccent'] = '2';
$conf['useheading'] = 1;
$conf['useacl'] = 1;
$conf['defaultgroup'] = 'users';
$conf['superuser'] = '@admin';
$conf['manager'] = '@manager';
$conf['disableactions'] = 'backlink,recent,revisions,check,subscribe,unsubscribe,source,export_raw';
$conf['htmlok'] = 1;
$conf['subscribers'] = 1;
$conf['gdlib'] = '1';
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
$conf['mailfrom'] = 'info@notomorrow.de';
$conf['compress'] = 0;
$conf['send404'] = 1;
$conf['sitemap'] = 1;
$conf['rss_type'] = 'rss2';
$conf['rss_linkto'] = 'current';
$conf['rss_content'] = 'html';
$conf['plugin']['blog']['namespace'] = 'news:archiv';
$conf['plugin']['blog']['dateprefix'] = '%d.%m.%Y - ';
$conf['plugin']['tag']['sortkey'] = 'cdate';
$conf['plugin']['tag']['sortorder'] = 'descending';
$conf['plugin']['tag']['pagelist_flags'] = 'list, date';
$conf['plugin']['discussion']['useavatar'] = '0';
$conf['plugin']['discussion']['urlfield'] = '1';
$conf['plugin']['pagelist']['showdesc'] = '160';
$conf['plugin']['pagelist']['showcomments'] = '1';
$conf['plugin']['pagelist']['showtags'] = '1';
$conf['welcome_page'] = 'welcome';

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
